Repository encaffeine/react-contribution-calendar, pull requests merged in 2023-08, with the labels that each got.

#15 feat: add 'textColor' attribute
  package.json
  src/components/Cell/index.tsx
  src/components/Label/index.tsx
  src/components/Table/index.tsx
  src/components/TableBody/index.tsx
  src/components/TableHead/index.tsx
  src/main.tsx
  src/types/react-contribution-calendar.d.ts
Labels: feature

#14 fix: cell background color
  package.json
  src/components/Cell/index.tsx
  src/components/Label/index.tsx
  src/components/Table/index.tsx
  src/components/TableBody/index.tsx
  src/components/TableHead/index.tsx
  src/components/index.ts
  src/main.tsx
  src/styles/colors.ts
  src/types/react-contribution-calendar.d.ts
Labels: fix

#16 docs: update README
  README.md
Labels: documentation

#17 build: cd for deploying to npm
  .github/workflows/deploy.yml
Labels: ci/cd

#18 테마를 추가하고, blue_pop과 dark_blue테마를 삭제했습니다.
  src/styles/colors.ts
Labels: design

#19 add neonpunk, citypop, coral theme
  src/styles/colors.ts
Labels: design

#20 feat: calendar range with start and end date
  .eslintrc.cjs
  package-lock.json
  package.json
  src/components/Table/index.tsx
  src/components/TableBody/index.tsx
  src/components/TableHead/index.tsx
  src/styles/colors.ts
  src/types/react-contribution-calendar.d.ts
  src/utils/index.ts
Labels: feature, fix

#21 release: v1.1.0
  README.md
  package.json
  src/types/react-contribution-calendar.d.ts
Labels: release

#24 refactor: main logics
  package.json
  src/components/Table/index.tsx
  src/components/TableBody/index.tsx
  src/components/TableHead/index.tsx
  src/types/react-contribution-calendar.d.ts
  src/utils/index.ts
Labels: refactoring, release

#25 feat: boundary cell style
  README.md
  package.json
  src/components/Table/index.tsx
  src/components/TableBody/index.tsx
  src/types/react-contribution-calendar.d.ts
Labels: design, feature

#26 feat: modify tooltip
  src/components/Cell/index.css
  src/components/Cell/index.tsx
  src/components/TableBody/index.tsx
  src/components/TableHead/index.tsx
  src/utils/index.ts
Labels: feature

#27 fix: cell boundary color
  src/components/TableBody/index.tsx
Labels: fix

#28 docs: updated README
  README.md
Labels: documentation

#30 release: v1.1.3
  package.json
Labels: release

#31 feat: update cell styles
  README.md
  package.json
  src/components/Cell/index.css
  src/components/Cell/index.tsx
  src/components/Label/index.css
  src/components/Table/index.css
  src/components/Table/index.tsx
  src/components/TableBody/index.tsx
  src/components/TableHead/index.tsx
  src/main.tsx
  src/types/react-contribution-calendar.d.ts
  src/types/types.d.ts
Labels: design, feature, release

#34 fix: tooltip not showing on chrome extension
  package.json
  src/components/Cell/index.css
  src/components/Cell/index.tsx
  src/components/Label/index.css
  src/components/Label/index.tsx
  src/types/react-contribution-calendar.d.ts
Labels: fix

#35 fix: cell stylings with collapsing table cells
  package-lock.json
  package.json
  src/components/Cell/index.css
  src/components/Cell/index.tsx
  src/components/Label/index.css
  src/components/Table/index.css
  src/components/Table/index.tsx
  src/components/TableBody/index.css
  src/components/TableBody/index.tsx
  src/components/TableHead/index.css
  src/components/TableHead/index.tsx
  src/index.css
  src/main.tsx
  src/types/react-contribution-calendar.d.ts
  src/utils/index.ts
Labels: fix, release

#37 fix: column head and tooltip position
  src/components/Cell/index.css
  src/components/Cell/index.tsx
  src/components/Label/index.tsx
  src/components/TableHead/index.tsx
Labels: fix

#38 feat: add emoji theme
  README.md
  images/blue_pop.png
  images/cherry.png
  images/cherry_blossom.png
  images/citypop.png
  images/coral.png
  images/dark_blue.png
  images/dark_cherry.png
  images/dark_cherry_blossom.png
  images/dark_citypop.png
  images/dark_coral.png
  images/dark_empty.png
  images/dark_grass.png
  images/dark_gray.png
  images/dark_halloween.png
  images/dark_mustard.png
  images/dark_neonpunk.png
  images/dark_ocean.png
  images/dark_pink.png
  images/dark_purquoise.png
  images/dark_sky.png
  images/dark_vomit.png
  images/dark_winter.png
  images/emoji_negative.png
  images/emoji_positive.png
  images/empty.png
  images/grass.png
  images/gray.png
  images/halloween.png
  images/mustard.png
  images/neonpunk.png
  images/ocean.png
  images/pink.png
  images/purquoise.png
  images/sky.png
  images/vomit.png
  images/winter.png
  package-lock.json
  package.json
  src/components/Cell/index.tsx
  src/components/TableBody/index.tsx
  src/styles/colors.ts
  src/types/react-contribution-calendar.d.ts
Labels: design, feature, release

#39 fix: table head
  README.md
  package-lock.json
  package.json
  src/components/Cell/index.css
  src/components/Cell/index.tsx
  src/components/Description/index.css
  src/components/Description/index.tsx
  src/components/Table/index.css
  src/components/Table/index.tsx
  src/components/TableBody/index.css
  src/components/TableBody/index.tsx
  src/components/TableHead/index.css
  src/components/TableHead/index.tsx
  src/index.css
  src/main.tsx
  src/types/react-contribution-calendar.d.ts
Labels: feature, fix, release

#40 fix: calendar padding
  package-lock.json
  package.json
  src/components/Cell/index.tsx
  src/components/Description/index.css
  src/components/Description/index.tsx
  src/components/Table/index.css
  src/components/Table/index.tsx
  src/components/TableBody/index.tsx
  src/main.tsx
  src/types/react-contribution-calendar.d.ts
Labels: fix, release

#42 feat: isTextTheme option
  src/components/Cell/index.tsx
  src/components/Description/index.tsx
  src/types/types.d.ts
Labels: feature

#41 feat: custom row
  README.md
  src/components/Table/index.tsx
  src/components/TableBody/index.tsx
  src/components/TableHead/index.css
  src/components/TableHead/index.tsx
  src/exceptions/index.ts
  src/main.tsx
  src/types/react-contribution-calendar.d.ts
Labels: feature

#43 feat: add scroll option
  README.md
  images/cherry.png
  images/cherry_blossom.png
  images/citypop.png
  images/coral.png
  images/dark_cherry.png
  images/dark_cherry_blossom.png
  images/dark_citypop.png
  images/dark_coral.png
  images/dark_empty.png
  images/dark_grass.png
  images/dark_gray.png
  images/dark_halloween.png
  images/dark_mustard.png
  images/dark_neonpunk.png
  images/dark_ocean.png
  images/dark_pink.png
  images/dark_purquoise.png
  images/dark_sky.png
  images/dark_vomit.png
  images/dark_winter.png
  images/emoji_negative.png
  images/emoji_positive.png
  images/empty.png
  images/grass.png
  images/gray.png
  images/halloween.png
  images/mustard.png
  images/neonpunk.png
  images/ocean.png
  images/pink.png
  images/purquoise.png
  images/sky.png
  images/vomit.png
  images/winter.png
  src/components/Table/index.css
  src/components/Table/index.tsx
  src/components/TableBody/index.tsx
  src/index.css
  src/main.tsx
  src/types/react-contribution-calendar.d.ts
Labels: feature
